name: Build & Publish Docker Image to Docker Hub (Development)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: production

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & Publish
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@master
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: peterlewis/wg-easy:development, peterlewis/wg-easy:nightly
