name: Build & Publish Docker Image to Docker Hub (Production)

on:
  workflow_dispatch:
  push:
    branches:
      - production
      - production/**

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        ref: production

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    # Set environment variables
    - run: echo RELEASE=$(cat ./src/package.json | jq -r .release) >> $GITHUB_ENV
    
    # Build & Publish
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@master
      with:
        push: true
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        tags: peterlewis/wg-easy:latest, pheiduck/wg-easy:${{ env.RELEASE }}
