name: Lint

on:
  push:
    branches:
      - main
      - production
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: 'current'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            src/package-lock.json

      - name: npm run lint
        run: |
          npm config set -g fund false
          cd src
          npm ci
          npm run lint
